services:
  my-portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-portfolio
    env_file: 
      - ./.env
    ports:
      - "8081:80"
    depends_on:
      - mysql
    volumes:
      - my-portfolio:/var/www/html
    networks:
      - my-portfolio
    
  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my-portfolio


volumes:
  mysql-data:
  my-portfolio:

networks:
  my-portfolio:
    driver: bridge
