name: Automation deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 55154
          script: |
            # 1. First fix permissions as normal user
            cd /var/www/html/MyBlog/My-Portfolio
            sudo chown -R $USER:www-data .
            sudo find . -type d -exec chmod 775 {} \;
            sudo find . -type f -exec chmod 664 {} \;
            
            # 2. Reset git repository
            git reset --hard
            git clean -fd
            git pull origin main
            
            # 3. Fix web server permissions
            sudo chown -R www-data:www-data storage/
            sudo chown -R www-data:www-data bootstrap/cache/
            sudo chmod -R 775 storage/
            sudo chmod -R 775 bootstrap/cache/
            
            # 4. Composer install
            composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
            
            # 5. Laravel maintenance
            sudo -u www-data php artisan optimize:clear
            sudo -u www-data php artisan view:cache
            sudo -u www-data php artisan config:cache
            sudo -u www-data php artisan route:cache
            
            # 6. Ensure log file exists
            sudo touch storage/logs/laravel.log
            sudo chown www-data:www-data storage/logs/laravel.log
            sudo chmod 664 storage/logs/laravel.log