name: Automation deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}  # Switch to SSH key authentication
          port: 55154
          script: |
            # Switch to web server user
            sudo -u www-data bash << 'EOF'
            cd /var/www/html/MyBlog/My-Portfolio
            
            # Reset git state
            git reset --hard
            git clean -fd
            
            # Pull changes
            git pull origin main
            
            # Fix composer permissions
            chown -R www-data:www-data /var/www/html/MyBlog/My-Portfolio/vendor
            chown -R www-data:www-data /var/www/html/MyBlog/My-Portfolio/composer.lock
            
            # Install dependencies
            composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
            
            # Laravel maintenance
            php artisan optimize:clear
            php artisan view:cache
            php artisan config:cache
            php artisan route:cache
            
            # Fix storage permissions
            chmod -R 775 storage/
            chmod -R 775 bootstrap/cache/
            EOF
            
            # Final permission fix
            sudo chown -R www-data:www-data /var/www/html/MyBlog/My-Portfolio
            sudo chmod -R 775 /var/www/html/MyBlog/My-Portfolio/storage
            sudo chmod -R 775 /var/www/html/MyBlog/My-Portfolio/bootstrap/cache