name: Automation deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 55154
          script: |
            cd /var/www/html/MyBlog/My-Portfolio
            git config --global --add safe.directory /var/www/html/MyBlog/My-Portfolio
            git stash
            git pull origin main
            git stash pop